# docker composerのバージョンの指定
version: "3.8"
services:
  front:
    # buildするdockerfileの位置
    build: .
    # 作成するdockerコンテナの名前
    container_name: react-front
    # docker内で共有するフォルダの指定
    volumes:
      - .:/to-do-app
    working_dir: /to-do-app
    # コンテナにバインドするポートの指定（左:ローカルのポート、右:dookerコンテナのポート）
    ports:
      - 3000:3000
    # コンテナが勝手に終了しないための設定
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
    # ホットリロードを行う設定
    environment:
      - WATCHPACK_POLLING=true