apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-api-server
  name: todo-api-server
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: todo-api-server
  type: ClusterIP
status:
  loadBalancer: {}